### ISSUE TITLE
Cannot see visualisation

### ISSUE THREAD

**Issue by brookebroccoli** [PerCollECT/CameraCopse#1]
Hi there, 

I've tried opening the camera visualisation but there is nothing in there to view. Please see attached image. 

Is there another link to the entire visualisation?

Thanks!

<img width="1324" alt="Screen Shot 2021-10-08 at 10 25 29 am" src="https://user-images.githubusercontent.com/33395020/136475536-39dccfce-0663-4e23-aabb-bd2d75a749c8.png">

**Comment by ClemensLinnhoff** [comment]
Hi,
sorry for the late reply.
That's because until now there is no effect data for camera unfortunately. So the visualization is working correctly. We are mainly working on radar and lidar at the moment.
Are you interested in working on PerCollECT for camera?

**Comment by ClemensLinnhoff** [comment]
We now created a working example for CameraCopse. It is mainly based on effects listed in [CV HAZOP](https://vitro-testing.com/cv-hazop/).
